### ISSUE TITLE
What about ln ?

### ISSUE THREAD

**Issue by C138** [thanoulis/tcalc#2]
Why not ln() instead of  log() 

and keeping log() == log10()

?

providing the three writings : ln() / log() and also log10()

**Comment by thanoulis** [comment]
You have a point.
It is now changed in [v1.2.1](https://github.com/thanoulis/tcalc/releases/tag/v1.2.1)
Behaves as expected:
- `ln()` is the natural logarithm
- `log()` is the decimal logarithm
- `log10()` still exists and behaves as before

Thank you for the notice.
